# RoleBinding to allow Plex ServiceAccount to create transcoder pods
# Update 'plex' to match your Plex ServiceAccount name
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-plex-transcoder
  labels:
    app.kubernetes.io/name: kube-plex
    app.kubernetes.io/component: transcoder
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-plex-transcoder
subjects:
  - kind: ServiceAccount
    name: plex  # Change this to your Plex ServiceAccount name
